import type { Property } from "@/lib/types";

export const demoProperties: Property[] = [
  {
    id: "demo-piantini",
    title: "Apartamento Premium en Piantini",
    slug: "apartamento-premium-piantini",
    description: "Apartamento contemporáneo con terminaciones premium, amplios espacios, lobby, gimnasio, piscina y excelente ubicación.",
    operation: "sale",
    status: "published",
    property_type: "Apartamento",
    price: 325000,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 3.5,
    parking_spaces: 2,
    area_m2: 210,
    city: "Santo Domingo",
    sector: "Piantini",
    country: "República Dominicana",
    featured: true,
    pool: true,
    amenities: ["Piscina", "Gimnasio", "Lobby", "Planta eléctrica"],
    property_images: [{
      url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },
  {
    id: "demo-jarabacoa",
    title: "Villa Moderna en Jarabacoa",
    slug: "villa-moderna-jarabacoa",
    description: "Villa privada rodeada de naturaleza, con vista a montaña, piscina, terraza y excelente potencial para vivienda o inversión vacacional.",
    operation: "sale",
    status: "published",
    property_type: "Villa",
    price: 410000,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 4,
    parking_spaces: 4,
    area_m2: 380,
    lot_m2: 1250,
    city: "Jarabacoa",
    province: "La Vega",
    country: "República Dominicana",
    featured: true,
    pool: true,
    amenities: ["Piscina", "Terraza", "Vista a montaña", "Jardín"],
    property_images: [{
      url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },
  {
    id: "demo-punta-cana",
    title: "Apartamento de Inversión en Punta Cana",
    slug: "apartamento-inversion-punta-cana",
    description: "Unidad orientada a inversión y renta vacacional en una zona turística de alta demanda, con piscina y amenidades.",
    operation: "sale",
    status: "published",
    property_type: "Apartamento",
    price: 185000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    parking_spaces: 1,
    area_m2: 105,
    city: "Punta Cana",
    province: "La Altagracia",
    country: "República Dominicana",
    featured: true,
    pool: true,
    amenities: ["Piscina", "Seguridad", "Área social"],
    property_images: [{
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },
  {
    id: "demo-santiago",
    title: "Penthouse en Cerros de Gurabo",
    slug: "penthouse-cerros-de-gurabo",
    description: "Penthouse amplio con terraza privada, cuatro habitaciones y espacios sociales generosos.",
    operation: "sale",
    status: "published",
    property_type: "Penthouse",
    price: 295000,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 4.5,
    parking_spaces: 3,
    area_m2: 330,
    city: "Santiago",
    sector: "Cerros de Gurabo",
    country: "República Dominicana",
    featured: false,
    amenities: ["Terraza privada", "Ascensor", "Seguridad"],
    property_images: [{
      url: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },

  {
    id: "demo-naco",
    title: "Apartamento Ejecutivo en Naco",
    slug: "apartamento-ejecutivo-naco",
    description: "Apartamento moderno de alto nivel en el corazón de Naco, diseñado para vivienda ejecutiva con excelente distribución, balcón, lobby climatizado y áreas sociales.",
    operation: "sale",
    status: "published",
    property_type: "Apartamento",
    price: 248000,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2.5,
    parking_spaces: 2,
    area_m2: 175,
    city: "Santo Domingo",
    sector: "Naco",
    province: "Distrito Nacional",
    country: "República Dominicana",
    featured: true,
    pool: true,
    amenities: [
      "Piscina",
      "Gimnasio",
      "Lobby",
      "Ascensor",
      "Seguridad 24 horas",
      "Planta eléctrica"
    ],
    property_images: [{
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },

  {
    id: "demo-bella-vista",
    title: "Apartamento Amueblado en Bella Vista",
    slug: "apartamento-amueblado-bella-vista",
    description: "Apartamento completamente amueblado para alquiler de largo plazo, próximo a centros comerciales, restaurantes y principales avenidas de Santo Domingo.",
    operation: "rent",
    status: "published",
    property_type: "Apartamento",
    price: 1900,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2.5,
    parking_spaces: 2,
    area_m2: 145,
    city: "Santo Domingo",
    sector: "Bella Vista",
    province: "Distrito Nacional",
    country: "República Dominicana",
    furnished: true,
    featured: false,
    amenities: [
      "Amueblado",
      "Lobby",
      "Gimnasio",
      "Ascensor",
      "Seguridad",
      "Área social"
    ],
    property_images: [{
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },

  {
    id: "demo-cap-cana",
    title: "Villa de Lujo en Cap Cana",
    slug: "villa-lujo-cap-cana",
    description: "Villa contemporánea de lujo en Cap Cana con amplias áreas sociales, piscina privada, jardín, terrazas y terminaciones de primera categoría.",
    operation: "sale",
    status: "published",
    property_type: "Villa",
    price: 1250000,
    currency: "USD",
    bedrooms: 5,
    bathrooms: 5.5,
    parking_spaces: 4,
    area_m2: 620,
    lot_m2: 1250,
    city: "Punta Cana",
    sector: "Cap Cana",
    province: "La Altagracia",
    country: "República Dominicana",
    featured: true,
    pool: true,
    amenities: [
      "Piscina privada",
      "Jardín",
      "Terraza",
      "Área BBQ",
      "Seguridad",
      "Cuarto de servicio"
    ],
    property_images: [{
      url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },

  {
    id: "demo-bavaro",
    title: "Condo Turístico en Bávaro",
    slug: "condo-turistico-bavaro",
    description: "Apartamento orientado a inversión y renta vacacional en Bávaro, con piscina, áreas recreativas y proximidad a zonas turísticas.",
    operation: "sale",
    status: "published",
    property_type: "Apartamento",
    price: 165000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    parking_spaces: 1,
    area_m2: 98,
    city: "Punta Cana",
    sector: "Bávaro",
    province: "La Altagracia",
    country: "República Dominicana",
    featured: true,
    pool: true,
    amenities: [
      "Piscina",
      "Área social",
      "Seguridad",
      "Lobby",
      "Renta vacacional"
    ],
    property_images: [{
      url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },

  {
    id: "demo-las-terrenas",
    title: "Apartamento Cerca del Mar en Las Terrenas",
    slug: "apartamento-mar-las-terrenas",
    description: "Apartamento tropical de dos habitaciones ideal para segunda vivienda o renta vacacional, localizado cerca de las principales playas de Las Terrenas.",
    operation: "sale",
    status: "published",
    property_type: "Apartamento",
    price: 285000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    parking_spaces: 1,
    area_m2: 130,
    city: "Las Terrenas",
    province: "Samaná",
    country: "República Dominicana",
    furnished: true,
    featured: true,
    pool: true,
    amenities: [
      "Piscina",
      "Terraza",
      "Amueblado",
      "Área tropical",
      "Seguridad"
    ],
    property_images: [{
      url: "https://images.unsplash.com/photo-1601918774946-25832a4be0d6?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },

  {
    id: "demo-casa-de-campo",
    title: "Villa Exclusiva en Casa de Campo",
    slug: "villa-exclusiva-casa-de-campo",
    description: "Residencia de lujo con diseño abierto, piscina privada, grandes jardines y amplias áreas sociales para un estilo de vida premium.",
    operation: "sale",
    status: "published",
    property_type: "Villa",
    price: 1850000,
    currency: "USD",
    bedrooms: 6,
    bathrooms: 7,
    parking_spaces: 5,
    area_m2: 850,
    lot_m2: 2100,
    city: "La Romana",
    sector: "Casa de Campo",
    province: "La Romana",
    country: "República Dominicana",
    featured: true,
    pool: true,
    amenities: [
      "Piscina",
      "Jacuzzi",
      "Jardín",
      "Terraza",
      "Área BBQ",
      "Cuarto de servicio",
      "Seguridad"
    ],
    property_images: [{
      url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },

  {
    id: "demo-puerto-plata",
    title: "Villa con Piscina en Puerto Plata",
    slug: "villa-piscina-puerto-plata",
    description: "Villa privada con piscina y espacios abiertos, apropiada para residencia familiar, inversión turística o renta vacacional.",
    operation: "sale",
    status: "published",
    property_type: "Villa",
    price: 375000,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 4,
    parking_spaces: 3,
    area_m2: 360,
    lot_m2: 780,
    city: "Puerto Plata",
    province: "Puerto Plata",
    country: "República Dominicana",
    featured: false,
    pool: true,
    amenities: [
      "Piscina",
      "Jardín",
      "Terraza",
      "Marquesina",
      "Área BBQ"
    ],
    property_images: [{
      url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },

  {
    id: "demo-la-vega",
    title: "Casa Familiar Moderna en La Vega",
    slug: "casa-familiar-moderna-la-vega",
    description: "Residencia familiar moderna con espacios amplios, patio, terraza y excelente distribución en una zona residencial de La Vega.",
    operation: "sale",
    status: "published",
    property_type: "Casa",
    price: 12900000,
    currency: "DOP",
    bedrooms: 4,
    bathrooms: 3.5,
    parking_spaces: 3,
    area_m2: 310,
    lot_m2: 520,
    city: "La Vega",
    province: "La Vega",
    country: "República Dominicana",
    featured: false,
    pool: false,
    amenities: [
      "Patio",
      "Terraza",
      "Marquesina",
      "Cisterna",
      "Área de lavado"
    ],
    property_images: [{
      url: "https://images.unsplash.com/photo-1600585152915-d208bec867a1?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },

  {
    id: "demo-juan-dolio",
    title: "Apartamento Frente al Mar en Juan Dolio",
    slug: "apartamento-frente-mar-juan-dolio",
    description: "Apartamento diseñado para disfrutar del Caribe con balcón, áreas sociales, piscina y acceso privilegiado a la zona de playa.",
    operation: "sale",
    status: "published",
    property_type: "Apartamento",
    price: 235000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    parking_spaces: 1,
    area_m2: 118,
    city: "Juan Dolio",
    province: "San Pedro de Macorís",
    country: "República Dominicana",
    featured: true,
    pool: true,
    amenities: [
      "Piscina",
      "Balcón",
      "Vista al mar",
      "Lobby",
      "Seguridad",
      "Ascensor"
    ],
    property_images: [{
      url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },

  {
    id: "demo-santo-domingo-este",
    title: "Casa Residencial en Santo Domingo Este",
    slug: "casa-residencial-santo-domingo-este",
    description: "Casa de dos niveles con distribución familiar, amplias habitaciones, terraza y área exterior para reuniones y actividades familiares.",
    operation: "sale",
    status: "published",
    property_type: "Casa",
    price: 9850000,
    currency: "DOP",
    bedrooms: 4,
    bathrooms: 3,
    parking_spaces: 2,
    area_m2: 280,
    lot_m2: 390,
    city: "Santo Domingo Este",
    province: "Santo Domingo",
    country: "República Dominicana",
    featured: false,
    pool: false,
    amenities: [
      "Terraza",
      "Patio",
      "Marquesina",
      "Cisterna",
      "Área de lavado"
    ],
    property_images: [{
      url: "https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1800&q=85",
      position: 0,
    }],
  },

  {
    id: "demo-solar-sde",
    title: "Solar Residencial de 800 m² en Santo Domingo Este",
    slug: "solar-residencial-800m2-santo-domingo-este",
    description: "Solar residencial amplio, apropiado para vivienda unifamiliar, pequeño proyecto residencial o inversión.",
    operation: "sale",
    status: "published",
    property_type: "Solar",
    price: 7200000,
    currency: "DOP",
    lot_m2: 800,
    land_tareas: 1.27,
    city: "Santo Domingo Este",
    sector: "San Isidro",
    province: "Santo Domingo",
    country: "República Dominicana",
    featured: true,
    amenities: [
      "Acceso asfaltado",
      "Electricidad",
      "Agua",
      "Zona residencial"
    ],
    property_images: [
      { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1800&q=85", position: 0 },
      { url: "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1800&q=85", position: 1 },
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1800&q=85", position: 2 },
      { url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1800&q=85", position: 3 },
      { url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1800&q=85", position: 4 },
      { url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1800&q=85", position: 5 }
    ],
  },

  {
    id: "demo-solar-santiago",
    title: "Solar Comercial de 1,500 m² en Santiago",
    slug: "solar-comercial-1500m2-santiago",
    description: "Terreno urbano con vocación comercial y acceso a vías principales de Santiago.",
    operation: "sale",
    status: "published",
    property_type: "Solar",
    price: 18500000,
    currency: "DOP",
    lot_m2: 1500,
    land_tareas: 2.39,
    city: "Santiago",
    province: "Santiago",
    country: "República Dominicana",
    featured: false,
    amenities: [
      "Acceso vial",
      "Energía eléctrica",
      "Zona urbana",
      "Vocación comercial"
    ],
    property_images: [
      { url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1800&q=85", position: 0 },
      { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1800&q=85", position: 1 }
    ],
  },

  {
    id: "demo-apto-construccion-piantini",
    title: "Apartamento en Construcción en Piantini",
    slug: "apartamento-construccion-piantini",
    description: "Apartamento dentro de una torre residencial en construcción, con terminaciones contemporáneas, áreas sociales y esquema de pago durante obra.",
    operation: "sale",
    status: "published",
    property_type: "Apartamento en construcción",
    construction_status: "under_construction",
    expected_delivery_date: "2028-06-30",
    price: 285000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2.5,
    parking_spaces: 2,
    area_m2: 135,
    city: "Santo Domingo",
    sector: "Piantini",
    province: "Distrito Nacional",
    country: "República Dominicana",
    featured: true,
    amenities: [
      "Lobby",
      "Piscina",
      "Gimnasio",
      "Ascensores",
      "Planta eléctrica"
    ],
    property_images: [
      { url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1800&q=85", position: 0 },
      { url: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1800&q=85", position: 1 },
      { url: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1800&q=85", position: 2 },
      { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1800&q=85", position: 3 }
    ],
  },

  {
    id: "demo-apto-preventa-punta-cana",
    title: "Apartamento en Preventa en Punta Cana",
    slug: "apartamento-preventa-punta-cana",
    description: "Unidad en desarrollo turístico orientada a inversión y renta vacacional, con precio de entrada en etapa de preventa.",
    operation: "sale",
    status: "published",
    property_type: "Apartamento en preventa",
    construction_status: "pre_sale",
    expected_delivery_date: "2027-12-15",
    price: 149000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    parking_spaces: 1,
    area_m2: 92,
    city: "Punta Cana",
    sector: "Bávaro",
    province: "La Altagracia",
    country: "República Dominicana",
    featured: true,
    pool: true,
    amenities: [
      "Piscina",
      "Área social",
      "Seguridad",
      "Renta vacacional"
    ],
    property_images: [
      { url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1800&q=85", position: 0 },
      { url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=85", position: 1 },
      { url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1800&q=85", position: 2 }
    ],
  },

  {
    id: "demo-finca-ganadera-la-vega",
    title: "Finca Ganadera de 85 Tareas en La Vega",
    slug: "finca-ganadera-85-tareas-la-vega",
    description: "Finca rural demostrativa con terreno para actividad ganadera, potreros, acceso interno y áreas para manejo de animales.",
    operation: "sale",
    status: "published",
    property_type: "Finca ganadera",
    price: 24000000,
    currency: "DOP",
    lot_m2: 53453.10,
    land_tareas: 85,
    city: "La Vega",
    sector: "Zona rural",
    province: "La Vega",
    country: "República Dominicana",
    animals_present: true,
    animals_description: "35 vacas, 2 toros y varios becerros dentro de la propiedad demostrativa.",
    featured: true,
    amenities: [
      "Potreros",
      "Corral",
      "Agua",
      "Acceso vehicular",
      "Área ganadera"
    ],
    property_images: [
      { url: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=1800&q=85", position: 0 },
      { url: "https://images.unsplash.com/photo-1545468258-576dbac5faa9?auto=format&fit=crop&w=1800&q=85", position: 1 },
      { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1800&q=85", position: 2 },
      { url: "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1800&q=85", position: 3 }
    ],
  },

  {
    id: "demo-terreno-agricola-san-juan",
    title: "Terreno Agrícola de 40 Tareas en San Juan",
    slug: "terreno-agricola-40-tareas-san-juan",
    description: "Terreno rural demostrativo con superficie expresada en tareas y metros cuadrados, apropiado para agricultura, ganadería o proyecto campestre.",
    operation: "sale",
    status: "published",
    property_type: "Terreno agrícola",
    price: 8800000,
    currency: "DOP",
    lot_m2: 25154.40,
    land_tareas: 40,
    city: "San Juan de la Maguana",
    province: "San Juan",
    country: "República Dominicana",
    animals_present: true,
    animals_description: "Caballos, chivos y gallinas presentes actualmente en el terreno demostrativo.",
    featured: false,
    amenities: [
      "Terreno agrícola",
      "Acceso rural",
      "Agua",
      "Vegetación",
      "Área para animales"
    ],
    property_images: [
      { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1800&q=85", position: 0 },
      { url: "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1800&q=85", position: 1 },
      { url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1800&q=85", position: 2 }
    ],
  },
];
