import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getPublicProperties } from "@/lib/data";
import type { Property } from "@/lib/types";
import { formatCurrency, normalizeText } from "@/lib/utils";
import { getModel, getOpenAI } from "@/lib/ai";
const schema=z.object({query:z.string().min(3).max(600)});
function score(query:string,p:Property){const tokens=normalizeText(query).split(/\s+/).filter(x=>x.length>=3);const hay=normalizeText([p.title,p.description,p.property_type,p.city,p.sector,p.province,p.country,p.bedrooms,p.bathrooms,p.area_m2,p.price,...(p.amenities??[])].filter(Boolean).join(" "));let s=0;for(const t of tokens)if(hay.includes(t))s++;if(p.featured)s+=.2;return s;}
export async function POST(req:NextRequest){try{const parsed=schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:"Consulta inválida."},{status:400});const inventory=await getPublicProperties();const ranked=inventory.map(p=>({p,s:score(parsed.data.query,p)})).sort((a,b)=>b.s-a.s);const useful=ranked.some(x=>x.s>0);const selected=(useful?ranked.filter(x=>x.s>0):ranked).slice(0,8).map(x=>x.p);const ai=getOpenAI();if(!ai)return NextResponse.json({answer:selected.length?`Encontré ${selected.length} opciones potenciales. Configura OPENAI_API_KEY para activar el análisis conversacional avanzado.`:"No encontré propiedades compatibles.",properties:selected});const context=selected.map((p,i)=>`${i+1}. ${p.title}\nUbicación: ${[p.sector,p.city,p.province].filter(Boolean).join(", ")}\nPrecio: ${formatCurrency(p.price,p.currency)}\nTipo: ${p.property_type}\nHabitaciones: ${p.bedrooms??"N/D"}\nBaños: ${p.bathrooms??"N/D"}\nÁrea: ${p.area_m2??"N/D"} m2\nAmenidades: ${(p.amenities??[]).join(", ")}`).join("\n\n");const response=await ai.responses.create({model:getModel(),input:`Eres Nexora AI, especialista en búsqueda inmobiliaria.\n\nCONSULTA:\n${parsed.data.query}\n\nINVENTARIO:\n${context||"Sin inventario"}\n\nResponde en español, máximo 180 palabras. No inventes propiedades, disponibilidad, rentabilidad ni datos ausentes. Explica qué opciones se acercan más y qué criterios no pueden verificarse.`});return NextResponse.json({answer:response.output_text||"Inventario analizado.",properties:selected});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"No fue posible procesar la búsqueda."},{status:500})}}
