import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { getOptionalUser } from "@/lib/auth";

const schema=z.object({property_id:z.string().uuid().optional(),name:z.string().min(2).max(150),email:z.string().email().or(z.literal("")).optional(),phone:z.string().max(50).optional(),whatsapp:z.string().max(50).optional(),notes:z.string().max(3000).optional(),source:z.string().max(100).optional().default("manual"),budget_min:z.coerce.number().nonnegative().optional(),budget_max:z.coerce.number().nonnegative().optional()});
function scoreLead(d:z.infer<typeof schema>){let score=25;if(d.phone)score+=10;if(d.whatsapp)score+=15;if(d.email)score+=10;if(d.budget_max)score+=15;if((d.notes?.length??0)>30)score+=10;return Math.min(score,100)}
export async function GET(){try{const auth=await getOptionalUser();if(!auth)return NextResponse.json({error:"No autorizado"},{status:401});const {data,error}=await auth.supabase.from("leads").select("*").order("created_at",{ascending:false});if(error)throw error;return NextResponse.json({leads:data??[]});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Error"},{status:500})}}
export async function POST(req:NextRequest){try{const parsed=schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:"Datos del prospecto inválidos."},{status:400});const d=parsed.data;const auth=await getOptionalUser();let organizationId:string;let assignedAgentId:string|null=null;let db:any;
if(auth){organizationId=auth.organizationId;assignedAgentId=auth.userId;db=auth.supabase;}else{if(!d.property_id)return NextResponse.json({error:"property_id es requerido para formularios públicos."},{status:400});const admin=createAdminClient();if(!admin)return NextResponse.json({error:"Supabase Admin no configurado."},{status:503});const {data:property,error}=await admin.from("properties").select("organization_id,agent_id,status").eq("id",d.property_id).eq("status","published").single();if(error||!property)return NextResponse.json({error:"Propiedad no encontrada."},{status:404});organizationId=property.organization_id;assignedAgentId=property.agent_id;db=admin;}
const {data:lead,error}=await db.from("leads").insert({organization_id:organizationId,property_id:d.property_id??null,assigned_agent_id:assignedAgentId,name:d.name,email:d.email||null,phone:d.phone||null,whatsapp:d.whatsapp||null,notes:d.notes||null,source:d.source||"manual",budget_min:d.budget_min??null,budget_max:d.budget_max??null,score:scoreLead(d),status:"new"}).select("*").single();if(error)throw error;await db.from("lead_events").insert({organization_id:organizationId,lead_id:lead.id,event_type:"lead_created",metadata:{source:d.source,property_id:d.property_id??null}});return NextResponse.json({lead},{status:201});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Error interno"},{status:500})}}
